"""empty message

Revision ID: 47c1b0900840
Revises: e9cce8677d9a
Create Date: 2018-11-30 20:48:08.924655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c1b0900840'
down_revision = 'e9cce8677d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('disease_heb', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diseases', 'disease_heb')
    # ### end Alembic commands ###
