"""empty message

Revision ID: e9cce8677d9a
Revises: edadd46f1f3e
Create Date: 2018-11-30 17:57:04.424526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cce8677d9a'
down_revision = 'edadd46f1f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('info', sa.String(), nullable=True))
    op.add_column('diseases', sa.Column('info_heb', sa.String(), nullable=True))
    op.add_column('diseases', sa.Column('wiki', sa.String(), nullable=True))
    op.add_column('diseases', sa.Column('wiki_heb', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diseases', 'wiki_heb')
    op.drop_column('diseases', 'wiki')
    op.drop_column('diseases', 'info_heb')
    op.drop_column('diseases', 'info')
    # ### end Alembic commands ###
