"""empty message

Revision ID: edadd46f1f3e
Revises: 
Create Date: 2018-11-10 23:08:26.752711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edadd46f1f3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('afula', sa.Integer(), nullable=True),
    sa.Column('akko', sa.Integer(), nullable=True),
    sa.Column('ashqelon', sa.Integer(), nullable=True),
    sa.Column('beer_sheva', sa.Integer(), nullable=True),
    sa.Column('hasharon', sa.Integer(), nullable=True),
    sa.Column('hadera', sa.Integer(), nullable=True),
    sa.Column('haifa', sa.Integer(), nullable=True),
    sa.Column('jerusalem', sa.Integer(), nullable=True),
    sa.Column('kinneret', sa.Integer(), nullable=True),
    sa.Column('nazareth', sa.Integer(), nullable=True),
    sa.Column('petach_tiqwa', sa.Integer(), nullable=True),
    sa.Column('ramla', sa.Integer(), nullable=True),
    sa.Column('rehovot', sa.Integer(), nullable=True),
    sa.Column('tel_aviv', sa.Integer(), nullable=True),
    sa.Column('zefat', sa.Integer(), nullable=True),
    sa.Column('idf', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('sumtotal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_date'), 'reports', ['date'], unique=False)
    op.create_index(op.f('ix_reports_disease_id'), 'reports', ['disease_id'], unique=False)
    op.create_index(op.f('ix_reports_week'), 'reports', ['week'], unique=False)
    op.create_index(op.f('ix_reports_year'), 'reports', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_year'), table_name='reports')
    op.drop_index(op.f('ix_reports_week'), table_name='reports')
    op.drop_index(op.f('ix_reports_disease_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_date'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('diseases')
    # ### end Alembic commands ###
